Repository EarthCubeInGeo/resen, pull requests merged in 2019-06, with the labels that each got.

#18 [ENH]: Set pulled image tag
  resen/Resen.py
Labels: enhancement

#16 [ENH]: First version of documentation
  README.rst
  docs/Makefile
  docs/commands.rst
  docs/conf.py
  docs/index.rst
  docs/installation.rst
  docs/make.bat
  docs/readme.rst
  docs/resen_consept.png
  docs/resen_consept.svg
  docs/usage.rst
Labels: enhancement

#21 Fix container storage path check
  resen/Resen.py
Labels: bug

#20 [ENH]: Progress bar when pulling images
  resen/Resen.py
Labels: enhancement

#23 [BUG]: docker.socket not platform independent
  resen/Resen.py
Labels: bug

#27 [ENH]: Guided bucket creation
  resen/resencmd.py
Labels: enhancement

#33 [ENH]: Guided create bucket finalized
  resen/Resen.py
  resen/resencmd.py
Labels: discussion
